[package]
name = "flip"
version = "0.1.0"
edition = "2021"
workspace = "../../"
authors.workspace = true

[dependencies]
anyhow = "1.0.86"
flip-libx11 = { version = "0.1.0", path = "../flip-libx11" }
